### PR TITLE
Revert breaking change in Redis constructor

### LINKED ISSUE #834: Breaking change introduced in 2.6.0
The `@keyv/redis` version `2.6.0` introduced a breaking change in its `constructor`:

[2.5.8](https://github.com/jaredwray/keyv/commit/2919dffb67bea0be191b808d1bec555c603b2539#diff-527f1bebf149d73557d6a3f71d9ec3e03819bff58f3e10fc818d65fb8c7c3d87L11):

```js
if ((uri.options && uri.options.family) || (uri.options && uri.isCluster)) {
```

[2.6.0](https://github.com/jaredwray/keyv/commit/2919dffb67bea0be191b808d1bec555c603b2539#diff-3602a763ab71b02221f86ada8a2295df13a6705994fb84bb215742a5d6283c44R25):

```ts
if (uri instanceof Redis) {
```

Here's how to reproduce it:

```ts
import KeyvRedis from '@keyv/redis';
import { Cluster } from 'ioredis';

const cluster = new Cluster([{ host: 'remote-redis-host' }], {
  scaleReads: 'all'
});

const keyvRedis = new KeyvRedis(cluster);
```

### PR DESCRIPTION
**Pull request by diogoazevedos**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Fixes #834

### CODE REVIEW

**Comment by diogoazevedos** [comment]
I'd like to cover this scenario, but I assume the `redisURI` is not Redis Cluster.

```ts
import {Cluster} from 'ioredis';

test.serial('should support cluster instance', t => {
	const cluster = new Cluster([{ host: redisURI }]);
	const keyv = new KeyvRedis(cluster);

	t.is(keyv.redis, cluster);
});
```

**Comment by jaredwray** [comment]
@diogoazevedos - thanks and we will get this fix out ASAP. Sorry for the break.

**Comment by jaredwray** [comment]
@diogoazevedos do you want to get a fix in for these errors?

```bash
> @keyv/redis
$ tsc --project tsconfig.dist.json
Error: src/index.ts(25,12): error TS23[39](https://github.com/jaredwray/keyv/actions/runs/5176158773/jobs/9329732824?pr=835#step:6:40): Property 'options' does not exist on type 'KeyvUriOptions'.
  Property 'options' does not exist on type 'string'.
Error: src/index.ts(25,27): error TS2339: Property 'options' does not exist on type 'KeyvUriOptions'.
  Property 'options' does not exist on type 'string'.
Error: src/index.ts(25,51): error TS2339: Property 'options' does not exist on type 'KeyvUriOptions'.
  Property 'options' does not exist on type 'string'.
Error: src/index.ts(25,66): error TS2339: Property 'isCluster' does not exist on type 'KeyvUriOptions'.
  Property 'isCluster' does not exist on type 'string'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /opt/hostedtoolcache/node/16.20.0/x64/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js run build
Directory: /home/runner/work/keyv/keyv/packages/redis
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.
```

**Comment by diogoazevedos** [comment]
@jaredwray on it 😄

**Pull request merged**
