### PR TITLE
fix(redis): add non set namespace support

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes namespaces not being respected when `useRedisSets` is false

### NOTES
- Happy to add tests if this is needed, some pointers on how/where to do so would be appreciated
- Should we first check that `this.namespace` is defined before using the function? I do not see this being done anywhere else.

### CODE REVIEW

**Review by christianllv — APPROVED** [review]

**Comment by jaredwray** [comment]
@ComfortablyCoding - thanks and we will deploy this in the next two to three weeks.

**Comment by ComfortablyCoding** [comment]
Thanks!

**Comment by ComfortablyCoding** [comment]
Hello @jaredwray, hope all is well.

It seems the changes from this PR were added in 2.8.1 but removed in 2.8.2+. They are still present in GitHub but are missing in the actual code release see https://unpkg.com/browse/@keyv/redis@2.8.3/dist/index.js. Is there any chance we can get a new release with these changes present?

**Comment by ComfortablyCoding** [comment]
Thanks!

**Pull request merged**
