### PR TITLE
refactor test-suite to use typescript

### PR DESCRIPTION
**Pull request by christianllv**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

### CODE REVIEW

**Comment by christianllv** [comment]
@jaredwray please, run the pipeline. I did a package.json update to do a build step before run tests.

**Comment by christianllv** [comment]
Hello @jaredwray,

I added the type property in package.json. About the second point, we have a build script (in the main workspace project) and a specific test-suites package.json. 

Can you check please, or should I add the script command in the pipeline?

**Comment by jaredwray** [comment]
> Hello @jaredwray,
> 
> I added the type property in package.json. About the second point, we have a build script (in the main workspace project) and a specific test-suites package.json.
> 
> Can you check please, or should I add the script command in the pipeline?

@christianllv what I am hoping for is something like `prepublish` so that when we do npm publish command it makes sure to build the dist folder before.

**Comment by christianllv** [comment]
@jaredwray I'm using prepare. Please check and let me know.

**Pull request merged**
