### PR TITLE
keyv - moving to minimal node engine support of 14

### PR DESCRIPTION
**Pull request by jaredwray**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/jaredwray/keyv/blob/main/CODE_OF_CONDUCT.md
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
keyv - moving to minimal node engine support of 14

### CODE REVIEW

**Comment by trevor-scheer** [comment]
I think this should be `engines.node` if you want package managers to enforce this. This is also a breaking change for users running < v14. I would highly recommend a major version bump to accompany this change.

**Comment by jaredwray** [comment]
@trevor-scheer - sorry as I should have not put that change live. Only `etcd` has that requirement at this time.

**Comment by jaredwray** [comment]
@trevor-scheer - v4.4.1 is now live without the requirement

**Comment by trevor-scheer** [comment]
No worries - I don't think this had any negative effect unless there's some specific tooling that looks at the node property. Just happened to notice the change. Appreciate the quick response!

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

**Pull request merged**
