### PR TITLE
Added async deserialize/serialize function types

### PR DESCRIPTION
**Pull request by cesarfd**
Added `Promise`d return types for `serialize` and `deserialize`.

### CODE REVIEW

**Comment by kaioduarte** [comment]
@jaredwray FYI, this change is breaking the Apollo server adapter

```ts
The types returned by 'serialize(...)' are incompatible between these types.
    Type 'string | Promise<string>' is not assignable to type 'string'.
        Type 'Promise<string>' is not assignable to type 'string'.
```

**Comment by jaredwray** [comment]
@kaioduarte - thanks for bringing this to our attention. Do you know what the recommended fix is? 

If not, I can dig in later this week to figure out what is the difference.

**Comment by jaredwray** [comment]
@kaioduarte - we have a fix that should go out for `4.3.2` today we believe. It is now on `main` if you want to validate.

**Comment by kaioduarte** [comment]
@jaredwray amazing, thank you!

**Pull request merged**
