### PR TITLE
offline: add typescript support

### PR DESCRIPTION
**Pull request by christianllv**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

### CODE REVIEW

**Review by jaredwray — CHANGES_REQUESTED** [review]
Do we want to use `any` in this? Could we define it better?

**Comment by christianllv** [comment]
In the args, I can define the first one I think, let me check.

**Comment by jaredwray** [comment]
> In the args, I can define the first one I think, let me check.

Can you see what is possible here? Otherwise we can merge this.

**Comment by christianllv** [comment]
I think that we need to merge. Because I don't know what data (args) the proxy can receive.

**Comment by jaredwray** [comment]
@christianllv - merged

**Pull request merged**
