### PR TITLE
Add valid constructor calls and arguments to types

### LINKED ISSUE #271: KeyV constructor type does not fully express its valid uses
Got a dependency bump PR for keyv over here: https://github.com/backstage/backstage/pull/10635 and it's failing on typescript errors for valid constructor calls, e.g.

```
25     client = new Keyv();
                ~~~~~~~~~~

  node_modules/keyv/src/index.d.ts:4:14
    4  constructor(uri: string, options: Keyv.Options);
                   ~~~~~~~~~~~
    An argument for 'uri' was not provided.
```

```
133     return new Keyv({
               ~~~~~~~~~~
134       namespace: pluginId,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
136       store: new KeyvRedis(this.connection),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
137     });
    ~~~~~~

  node_modules/keyv/src/index.d.ts:4:27
    4  constructor(uri: string, options: Keyv.Options);
                                ~~~~~~~~~~~~~~~~~~~~~
    An argument for 'options' was not provided.
```

### PR DESCRIPTION
**Pull request by iamEAP**
~~This covers my use-cases and most (all?) of those enumerated in the `README.md`, but doesn't necessarily cover everything the constructor actually may handle (e.g. compression options).~~

This copies over types from [https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/keyv/index.d.ts)

Closes #271

### CODE REVIEW

**Comment by thibauds** [comment]
Maybe we could use https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/keyv/index.d.ts ?

**Comment by jaredwray** [comment]
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/keyv/index.d.ts

I believe we should just move to having this file in the local repository. Do you want to move to that in this pull request and have us all validate it? 

The goal is to move more of this into the same repository and eventually we are considering moving to typescript but that will take time and we are weighing the benefits.

**Comment by iamEAP** [comment]
> Do you want to move to that in this pull request and have us all validate it?

Sounds good.  Done!  Please take a look when you've got a chance.

**Comment by jaredwray** [comment]
> > Do you want to move to that in this pull request and have us all validate it?
> 
> Sounds good. Done! Please take a look when you've got a chance.

I think you will need to run ‘xo —fix’ on this file

**Comment by iamEAP** [comment]
👍  `xo` was complaining on the naming of the generics (not strictly pascal case'd), so I chose to just remove the `T` prefixes.  Descriptive naming seems to be the recommendation: https://github.com/xojs/eslint-config-xo-typescript/issues/41

**Comment by jaredwray** [comment]
@iamEAP can you validate this change fixes the issue?

**Comment by trevor-scheer** [comment]
🤦‍♂️ sorry for the ping, I only looked at the GH releases and assumed this wasn't released. Trying out 4.2.2 now.

**Comment by trevor-scheer** [comment]
@jaredwray lgtm, thanks!

**Pull request merged**
