### PR TITLE
Update the has method for Map to support ttl

### PR DESCRIPTION
**Pull request by elliot40404**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Fix bug in keyv.has doesn't respect the ttl for the default in memory store

### CODE REVIEW

**Comment by jaredwray** [comment]
@elliot40404 - can you send in a unit test that shows where this would be needed so we can add it to this pull request?

**Comment by elliot40404** [comment]
I will add a unit test shortly

**Comment by elliot40404** [comment]
@jaredwray  Do you want me to add the unit test to the branch?

**Comment by jaredwray** [comment]
@elliot40404 - that would be great.

**Comment by elliot40404** [comment]
I have updated the branch to include the unit test. Thanks

**Comment by jaredwray** [comment]
@elliot40404 looks like you need to run `yarn xo --fix` to get the linting done.

**Comment by elliot40404** [comment]
Sorry my bad. That is now supposed to be fixed

**Comment by jaredwray** [comment]
@elliot40404 - do we know why it fails on this?

```
MemJS: Server <baduri:11211> failed after (2) retries with error - getaddrinfo EAI_AGAIN baduri

  Uncaught exception in test/test.ts

  Error: getaddrinfo EAI_AGAIN baduri

  ✘ test/test.ts exited with a non-zero exit code: 1
  ✔ types › can specify memcached store in typescript
  ─

  11 tests passed
  1 uncaught exception
error Command failed with exit code 1.```

is this happening in your local dev environment?

**Comment by elliot40404** [comment]
@jaredwray  Yes it also failed on my local env but I inferred that was because I didn't have memcached in my local environment. And from the error it looks like here it is the same problem probably originating due to this
```js
const keyvMemcache = new KeyvMemcache('localhost:11211'); // line 12 in /packages/keyv/test/test.ts
```

**Comment by jaredwray** [comment]
hi @elliot40404 - any update on this? If not, I will probably close this out.

**Comment by elliot40404** [comment]
@jaredwray Do you think it would be better if I create the same PR on the latest changes?

**Comment by jaredwray** [comment]
that would be great.
________________________________

**Comment by elliot40404** [comment]
Alright thanks @jaredwray . I will close this one a and create a new one.

**Pull request closed without merging**
