### PR TITLE
✨: add schema support

### PR DESCRIPTION
**Pull request by fuergaosi233**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add Schema support for https://github.com/jaredwray/keyv/issues/667

### CODE REVIEW

**Comment by jaredwray** [comment]
@fuergaosi233 - Thanks so much for the contribution!!! This overall looks good and ready to submit but was wondering if you could add in a unit test using the schema option with something other than `public` so it validates that it works. 

Let me know if you need help.

**Comment by jaredwray** [comment]
@fuergaosi233 - just following up if you can get a couple updated unit tests in for this new option.

**Comment by fuergaosi233** [comment]
Ok, I'll try that

**Comment by jaredwray** [comment]
@fuergaosi233 great! if you want I can look to add in the code also if you dont have time this week.

**Pull request merged**
