### PR TITLE
fixed sqlite bug

### LINKED ISSUE #336: sqlite error on random builds
We continue to see random errors on builds for sqlite3

```
FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
 1: 0xa3aaf0 node::Abort() [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
 2: 0x970199 node::FatalError(char const*, char const*) [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
 3: 0x9701a2  [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
 4: 0xa07ddb napi_fatal_error [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
 5: 0x7fae8ca3c3de  [/home/runner/work/keyv/keyv/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node]
 6: 0x7fae8ca3ca92 Napi::Error::ThrowAsJavaScriptException() const [/home/runner/work/keyv/keyv/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node]
 7: 0x7fae8ca3d017 Napi::Function::MakeCallback(napi_value__*, unsigned long, napi_value__* const*, napi_async_context__*) const [/home/runner/work/keyv/keyv/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node]
 8: 0x7fae8ca59e40 node_sqlite3::Statement::Work_AfterAll(napi_env__*, napi_status, void*) [/home/runner/work/keyv/keyv/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node]
 9: 0xa0a329 node::ThreadPoolWork::ScheduleWork()::{lambda(uv_work_s*, int)#2}::_FUN(uv_work_s*, int) [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
10: 0x13bc2fd  [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
11: 0x13c0a86  [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
12: 0x13d2ff4  [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
13: 0x13c13d8 uv_run [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
14: 0x9d1428 node::Environment::CleanupHandles() [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
15: 0x9d6b56 node::Environment::RunCleanup() [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
16: 0x9917f7 node::FreeEnvironment(node::Environment*) [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
17: 0xafd4af node::worker::Worker::Run() [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
18: 0xafd6f8  [/opt/hostedtoolcache/node/14.19.2/x64/bin/node]
19: 0x7fae9721e[609](https://github.com/jaredwray/keyv/runs/6500107069?check_suite_focus=true#step:6:610)  [/lib/x86_64-linux-gnu/libpthread.so.0]
20: 0x7fae97143163 clone [/lib/x86_64-linux-gnu/libc.so.6]
```

### PR DESCRIPTION
**Pull request by alphmth**
Fixes #336

### CODE REVIEW

**Comment by alphmth** [comment]
@jaredwray `workspaces` do not have an option to exclude a `package`. If I exclude a `package` it gives a `module not found ` error in other `packages` which are using that particular `package`.

**Comment by jaredwray** [comment]
@alphmth - thanks for looking at this and I am wondering if at this point we should switch to `npm workspaces` as we are seeing very little value in using `yarn`. Here is what would need to happen to make this work:

Docs: https://docs.npmjs.com/cli/v8/using-npm/workspaces

[ ] update the mono repo package to use npm workspaces. Example:
```json
  "scripts": {
    "test": "npm run test --workspaces"
    "test:services:start": "docker-compose -f ./docker-compose.yaml up -d",
    "test:services:stop": "docker-compose -f ./docker-compose.yaml down -v",
    "coverage": "npm run coverage --workspaces",
    "clean": "rm -rf node_modules && rm -rf package-lock.json &&  npm run clean --workspaces"
  }
```

[ ] update the `tests.yaml` to use npm moving forward
```yaml
      - name: Start Services
        run: npm run test:services:start

      - name: Install Dependencies  
        run: npm install
        
      - name: Test [keyv]
        run: npm run test --workspace=packages/keyv

      - name: Test [test-suite]
        run: npm run test --workspace=packages/test-suite

      - name: Test [etcd]
        run: npm run test --workspace=packages/etcd

      - name: Test [memcache]
        run: npm run test --workspace=packages/memcache

      - name: Test [mongo]
        run: npm run test --workspace=packages/mongo

      - name: Test [mysql]
        run: npm run test --workspace=packages/mysql

      - name: Test [offline]
        run: npm run test --workspace=packages/offline

      - name: Test [postgres]
        run: npm run test --workspace=packages/postgres

      - name: Test [redis]
        run: npm run test --workspace=packages/redis

      - name: Test [sqlite]
        run: npm run test --workspace=packages/sqlite

      - name: Test [tiered]
        run: npm run test --workspace=packages/tiered

      - name: Generate Code Coverage Report
        run: npm run coverage
```

This should help.

**Comment by alphmth** [comment]
@jaredwray Its not working in Node 12, 14

**Comment by jaredwray** [comment]
@alphmth - it looks like NPM is not working under Node 12 and 14. Can we try to install the latest NPM in the workflow to get it to do what we need?

**Comment by jaredwray** [comment]
@alphmth - was able to get this to work on yarn but still with the same issue on sqlite. Going to close this down.

**Pull request closed without merging**
