### PR TITLE
roll back changes

### LINKED ISSUE #242: Revert BigInt Changes
As per this comment https://github.com/jaredwray/keyv/pull/224#discussion_r798113681 we should revert the changes and instead provide the option to use a custom serializer/deserializer which we already provide. We just need to revert these changes.

### PR DESCRIPTION
**Pull request by alphmth**
Fixes #242

### CODE REVIEW

**Comment by alphmth** [comment]
@jaredwray should we add a test using custom serializer/deserializer and parsing `BigInt`?

**Comment by jaredwray** [comment]
@alphmth - let me know when you are ready for this be reviewed.

**Comment by bilalsha** [comment]
@jaredwray codecov uncovered line is covered in Memcache tests

**Comment by alphmth** [comment]
@jaredwray The CodeCov showing uncovered lines are covered in Memcache tests

**Pull request merged**
